//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODECOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonCodeDetail
    {
        public System.Guid CodeDetailId { get; set; }
        public System.Guid CodeId { get; set; }
        public short DetailSlot { get; set; }
        public string DetailInfo { get; set; }
        public string LanguageKey { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.Guid> CreatedMenuId { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.Guid> UpdatedMenuId { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> DeletedMenuId { get; set; }
    }
}
