//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODECOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysCodeHelper
    {
        public System.Guid CodeHelperId { get; set; }
        public string CodeHelperKey { get; set; }
        public string CodeHelperName { get; set; }
        public string LanguageKey { get; set; }
        public string ServiceDomain { get; set; }
        public string BizName { get; set; }
        public string MethodName { get; set; }
        public string Condition { get; set; }
        public string Description { get; set; }
        public bool IsUse { get; set; }
        public Nullable<bool> UseName { get; set; }
        public string NameHeaderText { get; set; }
        public Nullable<bool> UseValue { get; set; }
        public string ValueHeaderText { get; set; }
        public Nullable<bool> UseValue2 { get; set; }
        public string Value2HeaderText { get; set; }
        public Nullable<bool> UseValue3 { get; set; }
        public string Value3HeaderText { get; set; }
        public Nullable<bool> UseDescription { get; set; }
        public string SelectionMode { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.Guid> CreatedMenuId { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.Guid> UpdatedMenuId { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> DeletedMenuId { get; set; }
    }
}
