//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODECOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCode
    {
        public System.Guid UserCodeId { get; set; }
        public string CodeCategory { get; set; }
        public string CodeValue { get; set; }
        public string CodeName { get; set; }
        public string CodeDesc { get; set; }
        public string ClientFriendlyCodeName { get; set; }
        public bool IsUse { get; set; }
        public short SortOrder { get; set; }
        public string Info01 { get; set; }
        public string Info02 { get; set; }
        public string Info03 { get; set; }
        public string Info04 { get; set; }
        public string Info05 { get; set; }
        public string Info06 { get; set; }
        public string Info07 { get; set; }
        public string Info08 { get; set; }
        public string Info09 { get; set; }
        public string Info10 { get; set; }
        public string Info11 { get; set; }
        public string Info12 { get; set; }
        public string Info13 { get; set; }
        public string Info14 { get; set; }
        public string Info15 { get; set; }
        public string Info16 { get; set; }
        public string Info17 { get; set; }
        public string Info18 { get; set; }
        public string Info19 { get; set; }
        public string Info20 { get; set; }
        public string Info21 { get; set; }
        public string Info22 { get; set; }
        public string Info23 { get; set; }
        public string Info24 { get; set; }
        public string Info25 { get; set; }
        public string Info26 { get; set; }
        public string Info27 { get; set; }
        public string Info28 { get; set; }
        public string Info29 { get; set; }
        public string Info30 { get; set; }
        public string Info31 { get; set; }
        public string Info32 { get; set; }
        public string Info33 { get; set; }
        public string Info34 { get; set; }
        public string Info35 { get; set; }
        public string Info36 { get; set; }
        public string Info37 { get; set; }
        public string Info38 { get; set; }
        public string Info39 { get; set; }
        public string Info40 { get; set; }
        public string Info41 { get; set; }
        public string Info42 { get; set; }
        public string Info43 { get; set; }
        public string Info44 { get; set; }
        public string Info45 { get; set; }
        public string Info46 { get; set; }
        public string Info47 { get; set; }
        public string Info48 { get; set; }
        public string Info49 { get; set; }
        public string Info50 { get; set; }
        public string Info51 { get; set; }
        public string Info52 { get; set; }
        public string Info53 { get; set; }
        public string Info54 { get; set; }
        public string Info55 { get; set; }
        public string Info56 { get; set; }
        public string Info57 { get; set; }
        public string Info58 { get; set; }
        public string Info59 { get; set; }
        public string Info60 { get; set; }
        public string Info61 { get; set; }
        public string Info62 { get; set; }
        public string Info63 { get; set; }
        public string Info64 { get; set; }
        public string Info65 { get; set; }
        public string Info66 { get; set; }
        public string Info67 { get; set; }
        public string Info68 { get; set; }
        public string Info69 { get; set; }
        public string Info70 { get; set; }
        public string Info71 { get; set; }
        public string Info72 { get; set; }
        public string Info73 { get; set; }
        public string Info74 { get; set; }
        public string Info75 { get; set; }
        public string Info76 { get; set; }
        public string Info77 { get; set; }
        public string Info78 { get; set; }
        public string Info79 { get; set; }
        public string Info80 { get; set; }
        public string Info81 { get; set; }
        public string Info82 { get; set; }
        public string Info83 { get; set; }
        public string Info84 { get; set; }
        public string Info85 { get; set; }
        public string Info86 { get; set; }
        public string Info87 { get; set; }
        public string Info88 { get; set; }
        public string Info89 { get; set; }
        public string Info90 { get; set; }
        public string Info91 { get; set; }
        public string Info92 { get; set; }
        public string Info93 { get; set; }
        public string Info94 { get; set; }
        public string Info95 { get; set; }
        public string Info96 { get; set; }
        public string Info97 { get; set; }
        public string Info98 { get; set; }
        public string Info99 { get; set; }
        public string ExtraInfo { get; set; }
        public string CodeRemark { get; set; }
        public string LanguageKey { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.Guid> CreatedMenuId { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.Guid> UpdatedMenuId { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> DeletedMenuId { get; set; }
    }
}
